# ====================================================================
# Application Alerting Rules for SKC BI Dashboard
# Task 41.1: Critical alerts for 99.99% SLA monitoring
# ====================================================================

groups:
  # ====================================================================
  # APPLICATION AVAILABILITY AND PERFORMANCE
  # ====================================================================
  - name: application.rules
    rules:
      # High-level SLA monitoring
      - alert: ApplicationDown
        expr: up{job="nextjs-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: skc-bi-dashboard
          sla_impact: "true"
        annotations:
          summary: "SKC BI Dashboard application is down"
          description: "The main application has been down for more than 1 minute. This impacts our 99.99% SLA."
          runbook_url: "https://docs.company.com/runbooks/application-down"

      - alert: HighErrorRate
        expr: (rate(http_requests_total{job="nextjs-app",status=~"5.."}[5m]) / rate(http_requests_total{job="nextjs-app"}[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
          service: skc-bi-dashboard
          sla_impact: "true"
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes, which exceeds our 5% threshold."

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="nextjs-app"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: skc-bi-dashboard
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s, which exceeds our 2s threshold."

      - alert: SLABreach
        expr: (
          (1 - (
            (rate(http_requests_total{job="nextjs-app",status!~"5.."}[5m]) / rate(http_requests_total{job="nextjs-app"}[5m])) * 
            (sum(up{job="nextjs-app"}) / count(up{job="nextjs-app"}))
          )) * 100
        ) > 0.01
        for: 1m
        labels:
          severity: critical
          service: skc-bi-dashboard
          sla_impact: "true"
        annotations:
          summary: "99.99% SLA breach detected"
          description: "Current error budget breach: {{ $value | humanizePercentage }}. Immediate action required."

  # ====================================================================
  # DATABASE PERFORMANCE AND AVAILABILITY
  # ====================================================================
  - name: database.rules
    rules:
      - alert: DatabaseConnectionsHigh
        expr: (pg_stat_database_numbackends / pg_settings_max_connections) > 0.8
        for: 5m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "High database connection usage"
          description: "Database connections are at {{ $value | humanizePercentage }} of maximum capacity."

      - alert: DatabaseSlowQueries
        expr: rate(pg_stat_statements_total_time[5m]) / rate(pg_stat_statements_calls[5m]) > 1000
        for: 5m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "Slow database queries detected"
          description: "Average query time is {{ $value }}ms, which may impact application performance."

      - alert: DatabaseReplicationLag
        expr: pg_replication_lag_seconds > 30
        for: 2m
        labels:
          severity: critical
          service: postgresql
        annotations:
          summary: "Database replication lag is high"
          description: "Replication lag is {{ $value }}s, which may affect data consistency."

  # ====================================================================
  # SYSTEM RESOURCE MONITORING
  # ====================================================================
  - name: system.rules
    rules:
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) > 0.85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Low disk space detected"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}:{{ $labels.mountpoint }}"

      - alert: DiskSpaceCritical
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) > 0.95
        for: 1m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Critical disk space detected"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}:{{ $labels.mountpoint }}. Immediate action required."

  # ====================================================================
  # CONTAINER AND DOCKER MONITORING
  # ====================================================================
  - name: containers.rules
    rules:
      - alert: ContainerDown
        expr: up{job="cadvisor"} == 0
        for: 1m
        labels:
          severity: critical
          service: docker
        annotations:
          summary: "Container monitoring is down"
          description: "cAdvisor container monitoring has been down for more than 1 minute."

      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "Container CPU usage is high"
          description: "Container {{ $labels.name }} CPU usage is {{ $value | humanizePercentage }}"

      - alert: ContainerHighMemory
        expr: (container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""}) > 0.85
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "Container memory usage is high"
          description: "Container {{ $labels.name }} memory usage is {{ $value | humanizePercentage }}"

  # ====================================================================
  # BUSINESS METRICS AND CUSTOM ALERTS
  # ====================================================================
  - name: business.rules
    rules:
      - alert: LowActiveUsers
        expr: active_users_count < 10
        for: 10m
        labels:
          severity: warning
          service: business
        annotations:
          summary: "Low active user count"
          description: "Active user count ({{ $value }}) is below expected threshold during business hours."

      - alert: HighAPILatency
        expr: histogram_quantile(0.99, rate(api_request_duration_seconds_bucket{endpoint=~"/api/.*"}[5m])) > 5
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High API latency detected"
          description: "99th percentile API latency is {{ $value }}s for {{ $labels.endpoint }}"

      - alert: FailedDataRefresh
        expr: time() - last_data_refresh_timestamp > 3600
        for: 5m
        labels:
          severity: critical
          service: data-pipeline
        annotations:
          summary: "Data refresh has failed"
          description: "Data has not been refreshed for {{ $value | humanizeDuration }}. This may affect dashboard accuracy."

  # ====================================================================
  # SECURITY AND COMPLIANCE ALERTS
  # ====================================================================
  - name: security.rules
    rules:
      - alert: UnauthorizedAccess
        expr: rate(http_requests_total{status="401"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High rate of unauthorized access attempts"
          description: "{{ $value }} unauthorized access attempts per second detected."

      - alert: SuspiciousActivity
        expr: rate(http_requests_total{status="403"}[5m]) > 5
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Suspicious activity detected"
          description: "{{ $value }} forbidden access attempts per second, possible security threat."

      - alert: RateLimitBreached
        expr: rate(rate_limit_exceeded_total[5m]) > 0
        for: 1m
        labels:
          severity: info
          service: security
        annotations:
          summary: "Rate limit exceeded"
          description: "Rate limiting is actively protecting the application. {{ $value }} requests per second are being blocked."

  # ====================================================================
  # EXTERNAL SERVICES AND DEPENDENCIES
  # ====================================================================
  - name: external.rules
    rules:
      - alert: ExternalServiceDown
        expr: probe_success{job="blackbox-http"} == 0
        for: 3m
        labels:
          severity: critical
          service: external
        annotations:
          summary: "External service is unreachable"
          description: "{{ $labels.instance }} has been unreachable for more than 3 minutes."

      - alert: SlowExternalService
        expr: probe_duration_seconds{job="blackbox-http"} > 10
        for: 5m
        labels:
          severity: warning
          service: external
        annotations:
          summary: "External service is slow"
          description: "{{ $labels.instance }} response time is {{ $value }}s"

  # ====================================================================
  # PROMETHEUS AND MONITORING STACK HEALTH
  # ====================================================================
  - name: monitoring.rules
    rules:
      - alert: PrometheusConfigReloadFailed
        expr: prometheus_config_last_reload_successful != 1
        for: 5m
        labels:
          severity: warning
          service: prometheus
        annotations:
          summary: "Prometheus configuration reload failed"
          description: "Prometheus configuration reload has failed. Check the configuration file."

      - alert: PrometheusNotConnectedToAlertmanager
        expr: prometheus_notifications_alertmanagers_discovered < 1
        for: 5m
        labels:
          severity: critical
          service: prometheus
        annotations:
          summary: "Prometheus is not connected to Alertmanager"
          description: "Prometheus is not connected to any Alertmanager instance."

      - alert: AlertmanagerDown
        expr: up{job="alertmanager"} == 0
        for: 5m
        labels:
          severity: critical
          service: alertmanager
        annotations:
          summary: "Alertmanager is down"
          description: "Alertmanager has been down for more than 5 minutes. No alerts will be sent."

      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 5m
        labels:
          severity: warning
          service: grafana
        annotations:
          summary: "Grafana is down"
          description: "Grafana has been down for more than 5 minutes. Dashboards are unavailable."

  # ====================================================================
  # STORAGE AND BACKUP ALERTS
  # ====================================================================
  - name: storage.rules
    rules:
      - alert: BackupFailed
        expr: time() - last_backup_timestamp > 86400
        for: 1m
        labels:
          severity: critical
          service: backup
        annotations:
          summary: "Backup has failed or is overdue"
          description: "No successful backup detected in the last 24 hours."

      - alert: StorageIOHigh
        expr: rate(node_disk_io_time_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          service: storage
        annotations:
          summary: "High storage I/O detected"
          description: "Storage I/O utilization is {{ $value | humanizePercentage }} on {{ $labels.instance }}" 